#pragma once
#include <array>
struct SfBossProfile {
    const char *name;
    int index,family,tier,planet,backdrop;
    float health,interval,shotSpeed,damage;
};
inline constexpr std::array<const char*,50> sfBossNames{{
    "IRIS DE QUARTZ","SCARABEE CENDRE","MEDUSE DU VIDE","GUEULE DE BRAISE","ETOILE DE GIVRE",
    "MANTA D ACIER","REINE DES SPORES","HYDRE PLASMA","SCORPION OBSIDIEN","VEILLEUR ANCIEN",
    "PRISME HURLEUR","SCARABEE TITANE","ORACLE ABYSSAL","FOURNAISE ERRANTE","LEVIATHAN POLAIRE",
    "LAME CELESTE","RUCHER TOXIQUE","HYDRE IONIQUE","DARD DE NUIT","TITAN AUX TROIS YEUX",
    "COURONNE DE CRISTAL","COLOSSE CARAPACE","TISSEUSE DU NEANT","DEVOREUR MAGMATIQUE","DRAGON DE BANQUISE",
    "FAUCHEUSE ORBITALE","MATRICE VENENEUSE","HYDRE AUX NEUF FEUX","EMPEREUR SCORPION","ARCHON DES ETOILES",
    "SOUVERAIN PRISMATIQUE","BASTION VIVANT","MEDUSE DES ECLIPSES","SOLEIL CARNASSIER","MONARQUE DU ZERO",
    "SERAPHIN MECANIQUE","IMPERATRICE DES RONCES","HYDRE DES TEMPETES","TYRAN D OBSIDIENNE","GARDIEN DES SINGULARITES",
    "OEIL DE L INFINI","FORTERESSE CHITINE","CONSCIENCE DU VIDE","COEUR DE SUPERNOVA","HIVER ETERNEL",
    "ANGE DE L ANTIMATIERE","REINE DU DERNIER MONDE","HYDRE DES CINQUANTE SOLEILS","SCORPION APOCALYPSE","LE DERNIER COSMOS"
}};
inline constexpr std::array<const char*,10> sfBossHints{{
    "SALVES : CHANGEZ DE CAP","SPIRALES : CHANGEZ DE COULOIR","ANNEAUX : CHERCHEZ L OUVERTURE",
    "RAYON : BOUGEZ APRES LE SIGNAL","MINES : GARDEZ VOS DISTANCES","CROIX TOURNANTES : DECALEZ VOUS",
    "SPORES GUIDEES : CHANGEZ DE CAP","VAGUES : CHERCHEZ UN PASSAGE","ONDE : SORTEZ DU CERCLE",
    "SATELLITES : SURVEILLEZ LES FLANCS"
}};
static const std::array<SfBossProfile,50> &sfBossCatalog()
{
    static const auto catalog=[] {
        std::array<SfBossProfile,50> out{};
        for (int i=0;i<50;++i) out[i]={sfBossNames[i],i,i%10,i/10,i,(i%10+i/10)%6,
            900.0f+72*i+2*i*i,1.75f-.021f*i,.24f+.004f*i,12.0f+.6f*i};
        return out;
    }();
    return catalog;
}
